# Generated by Django 3.0.2 on 2020-02-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default='e41b9321-0f6f-43d4-8b81-e92403905155', help_text='Unique uuid', max_length=40, unique=True, verbose_name='UUID')),
                ('image', models.ImageField(blank=True, default=None, help_text='Carrier', null=True, upload_to='')),
                ('text', models.TextField(blank=True, default=None, help_text='Payload', null=True)),
            ],
        ),
    ]
