# Generated by Django 3.0.2 on 2020-02-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0004_auto_20200203_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default='c70f8c5e-5c58-41cd-a2cf-7d041dc269dc', help_text='Unique uuid', max_length=40, unique=True, verbose_name='UUID')),
                ('image', models.ImageField(blank=True, default=None, help_text='Carrier', null=True, upload_to='photos')),
                ('text', models.TextField(blank=True, default=None, help_text='Payload', null=True)),
                ('payload', models.TextField(blank=True, default=None, help_text='Compressed payload', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default='cc4f296f-0c63-4012-a211-b94d65f776a2', help_text='Unique uuid', max_length=40, unique=True, verbose_name='UUID')),
                ('image', models.ImageField(blank=True, default=None, help_text='Carrier', null=True, upload_to='photos')),
                ('text', models.TextField(blank=True, default=None, help_text='Payload', null=True)),
                ('payload', models.TextField(blank=True, default=None, help_text='Compressed payload', null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedImage',
        ),
    ]
