# Generated by Django 3.0.2 on 2020-02-04 01:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0005_auto_20200203_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embedimage',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Unique uuid', unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='extractimage',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, help_text='Unique uuid', unique=True, verbose_name='UUID'),
        ),
    ]
